# Generated by Django 2.2.12 on 2021-07-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_importer', '0003_products_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
