# Generated by Django 2.2.12 on 2021-07-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_importer', '0004_auto_20210731_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
