# Generated by Django 2.2.12 on 2021-07-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_importer', '0010_auto_20210731_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
