# Generated by Django 2.2.12 on 2021-07-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_importer', '0011_auto_20210731_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
