# Generated by Django 2.2.12 on 2021-08-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_importer', '0013_auto_20210731_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
