# Generated by Django 2.2.12 on 2021-08-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.IntegerField(default=0)),
            ],
        ),
    ]
